# Generated by Django 5.0.7 on 2024-07-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='numReviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
